package AddModule;


/**
* AddModule/Add.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Add.idl
* Sunday, May 10, 2026 11:17:34 PM IST
*/

public interface Add extends AddOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Add
