package AddModule;


/**
* AddModule/AddHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Add.idl
* Sunday, May 10, 2026 11:17:34 PM IST
*/

abstract public class AddHelper
{
  private static String  _id = "IDL:AddModule/Add:1.0";

  public static void insert (org.omg.CORBA.Any a, AddModule.Add that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AddModule.Add extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AddModule.AddHelper.id (), "Add");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AddModule.Add read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AddStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AddModule.Add value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AddModule.Add narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AddModule.Add)
      return (AddModule.Add)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AddModule._AddStub stub = new AddModule._AddStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AddModule.Add unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AddModule.Add)
      return (AddModule.Add)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AddModule._AddStub stub = new AddModule._AddStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
