package AddModule;

/**
* AddModule/AddHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Add.idl
* Sunday, May 10, 2026 11:17:34 PM IST
*/

public final class AddHolder implements org.omg.CORBA.portable.Streamable
{
  public AddModule.Add value = null;

  public AddHolder ()
  {
  }

  public AddHolder (AddModule.Add initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AddModule.AddHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AddModule.AddHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AddModule.AddHelper.type ();
  }

}
