package AddModule;


/**
* AddModule/AddOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Add.idl
* Sunday, May 10, 2026 11:17:34 PM IST
*/

public interface AddOperations 
{
  int addNumbers (int a, int b);
} // interface AddOperations
